const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
function pdf() {
  const stream = "BT /F1 18 Tf 20 150 Td (Comprovante sintetico) Tj ET";
  const objects = ["<< /Type /Catalog /Pages 2 0 R >>", "<< /Type /Pages /Kids [3 0 R] /Count 1 >>", "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 200] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>", "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>", `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`];
  let text = "%PDF-1.4\n";
  const offsets = [0];
  objects.forEach((object, i) => { offsets.push(Buffer.byteLength(text)); text += `${i + 1} 0 obj\n${object}\nendobj\n`; });
  const xref = Buffer.byteLength(text);
  text += `xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map(n => `${String(n).padStart(10,"0")} 00000 n \n`).join("")}trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;
  return Buffer.from(text);
}
module.exports = async ({ page, invoke, button, output, fileDialog }) => {
  const balances = await invoke("get_balances");
  await button("Transações").click();
  await page.getByRole("button", {name: /^Anexos de /}).first().click();
  const dialog = page.getByRole("dialog", {name:/^Anexos/});
  const original = path.join(output, "comprovante.pdf");
  fs.writeFileSync(original, pdf());
  await button("Adicionar anexo").click();
  await fileDialog(original);
  await button("Abrir comprovante.pdf").waitFor();
  fs.unlinkSync(original);
  await page.context().setOffline(true);
  await button("Abrir comprovante.pdf").click();
  await page.getByRole("img", { name: "Página 1 do PDF" }).waitFor();
  await page.getByText("Texto extraído da página").click();
  await page.getByText("Comprovante sintetico", { exact: true }).waitFor();
  await page.screenshot({path:path.join(output,"attachment-pdf.png")});
  assert.ok(await page.locator("canvas").evaluate(canvas => {
    const pixels = canvas.getContext("2d").getImageData(0,0,canvas.width,canvas.height).data;
    return pixels.some((value,index) => index % 4 !== 3 && value < 150);
  }));
  await page.context().setOffline(false);
  await button("Fechar visualização").click();
  const png = path.join(output,"recibo.png");
  fs.writeFileSync(png,Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aS1sAAAAASUVORK5CYII=","base64"));
  await button("Adicionar anexo").click();
  await fileDialog(png);
  await button("Abrir recibo.png").click();
  await page.getByAltText("Anexo recibo.png").waitFor();
  await page.waitForFunction(() => document.querySelector('img[alt="Anexo recibo.png"]')?.naturalWidth === 1);
  await button("Remover recibo.png").click();
  await button("Manter anexo").click();
  await button("Remover recibo.png").click();
  await button("Confirmar remoção de anexo").click();
  await page.getByText("Anexo removido.").waitFor();
  assert.ok(fs.existsSync(png));
  await button("Adicionar anexo").click();
  await fileDialog("",true);
  await page.getByText("Seleção cancelada.").waitFor();
  const description = (await dialog.getByRole("heading",{level:2}).textContent()).replace("Anexos — ","");
  const transaction = (await invoke("list_transactions")).find(t => t.description === description);
  const txFiles = await invoke("list_attachments",{kind:"transaction",id:transaction.id,page:0});
  assert.equal(txFiles.length,1);
  await dialog.getByRole("button", {name:"Fechar",exact:true}).click();
  await button("Cartões").click();
  await page.getByLabel("Exibir cartões").selectOption("all");
  await button("Compras e faturas de Validação compras").click();
  await page.getByRole("button",{name:/^Anexos de /}).first().click();
  await button("Adicionar anexo").click();
  await fileDialog(png);
  await button("Abrir recibo.png").waitFor();
  const purchaseDescription = (await dialog.getByRole("heading",{level:2}).textContent()).replace("Anexos — ","");
  const card=(await invoke("list_cards")).find(c=>c.name === "Validação compras");
  const purchases=await invoke("query_purchases",{cardId:card.id,page:0});
  const purchase=purchases.items.find(p=>p.description===purchaseDescription);
  const purchaseFiles=await invoke("list_attachments",{kind:"purchase",id:purchase.id,page:0});
  assert.equal(purchaseFiles.length,1);
  await dialog.getByRole("button",{name:"Fechar",exact:true}).click();
  await button("Voltar aos cartões").click();
  assert.deepEqual(await invoke("get_balances"), balances);
  const settings = await invoke("get_settings");
  for (const theme of ["light", "dark", "system"]) {
    await invoke("save_settings",{input:{...settings,theme},confirmCurrencyChange:false});
    await page.reload();
    await button("Transações").click();
    await button(`Anexos de ${description}`).click();
    await button("Abrir comprovante.pdf").click();
    await page.getByRole("img",{name:"Página 1 do PDF"}).waitFor();
    await page.evaluate(fs.readFileSync(require.resolve("axe-core/axe.min.js"),"utf8"));
    const violations=await page.evaluate(async()=> (await axe.run(document.querySelector('dialog[open]'),{runOnly:{type:"tag",values:["wcag2a","wcag2aa","wcag21aa"]}})).violations);
    assert.deepEqual(violations,[]);
    await page.screenshot({path:path.join(output,`attachments-${theme}.png`)});
    await dialog.getByRole("button",{name:"Fechar",exact:true}).click();
  }
  fs.writeFileSync(path.join(output,"attachments-result.json"),JSON.stringify({status:"passed",pdfOffline:true,axeThemes:3,transactionId:transaction.id,purchaseId:purchase.id}));
  return await Promise.all([...txFiles,...purchaseFiles].map(a=>invoke("read_attachment",{id:a.id})));
};
